name: Build Android APK with Remote Control

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Позволяет запустить вручную

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses || true
      
    - name: Install SDK components
      run: sdkmanager "platforms;android-34" "platforms;android-23" "build-tools;34.0.0"
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build APK
      run: ./gradlew assembleDebug --stacktrace
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: call-display-modifier-v2
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - name: Display APK info
      run: |
        echo "✅ APK successfully built!"
        ls -lh app/build/outputs/apk/debug/app-debug.apk

